### PR TITLE
Check if document has a date property before querying.

### LINKED ISSUE #29: Accessing undefined method "date"
The fix for #12 in [paginationModel.rb#L230](https://github.com/sverrirs/jekyll-paginate-v2/blob/master/lib/jekyll-paginate-v2/generator/paginationModel.rb#L230) assumes that all Jekyll::Document objects have a `date` property. For the [F-Droid website](https://gitlab.com/fdroid/fdroid-website) we have a generator which outputs one page per Android application in our website. These don't have a date, and so it fails with the following error:

```
/home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-paginate-v2-1.8.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:230:in `block in paginate': undefined method `date' for #<Jekyll:Page @name="subreddit.android.appstore/index.html"> (NoMethodError)
Did you mean?  data
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-paginate-v2-1.8.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:229:in `each'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-paginate-v2-1.8.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:229:in `paginate'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-paginate-v2-1.8.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:67:in `block in run'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-paginate-v2-1.8.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:34:in `each'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-paginate-v2-1.8.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:34:in `run'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-paginate-v2-1.8.0/lib/jekyll-paginate-v2/generator/paginationGenerator.rb:129:in `generate'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:174:in `block in generate'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:172:in `each'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:172:in `generate'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:68:in `process'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bundler/gems/polyglot-ea0b78b397e8/lib/jekyll/polyglot/patches/jekyll/site.rb:66:in `process_active_language'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bundler/gems/polyglot-ea0b78b397e8/lib/jekyll/polyglot/patches/jekyll/site.rb:57:in `process_language'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bundler/gems/polyglot-ea0b78b397e8/lib/jekyll/polyglot/patches/jekyll/site.rb:24:in `block (2 levels) in process'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bundler/gems/polyglot-ea0b78b397e8/lib/jekyll/polyglot/patches/jekyll/site.rb:23:in `fork'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bundler/gems/polyglot-ea0b78b397e8/lib/jekyll/polyglot/patches/jekyll/site.rb:23:in `block in process'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bundler/gems/polyglot-ea0b78b397e8/lib/jekyll/polyglot/patches/jekyll/site.rb:22:in `each'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bundler/gems/polyglot-ea0b78b397e8/lib/jekyll/polyglot/patches/jekyll/site.rb:22:in `process'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/command.rb:26:in `process_site'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/commands/build.rb:63:in `build'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/commands/build.rb:34:in `process'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/commands/serve.rb:37:in `block (2 levels) in init_with_program'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/gems/jekyll-3.4.3/exe/jekyll:13:in `<top (required)>'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bin/jekyll:22:in `load'
	from /home/pete/code/fdroid/website/vendor/ruby/2.3.0/bin/jekyll:22:in `<main>'
```

I'm happy to submit a PR which wrapped the relevant block of code in something like `if p.responds_to? "date"`, but my Ruby knowledge is not strong enough to know if that is an idiomatic way to solve this problem.

### PR DESCRIPTION
**Pull request by pserwylo**
The thing being asked for a `date` property is a `Jekyll::Document`.
Not all documents have a date (though most tend to), so this adds a
cautionary check.

As discussed in #29, I'm not sure of how idiomatic this type of check is. I have tested locally that it no longer crashes when hitting this code when paginating collections which don't have dates. I've also successfully built your three example sites in `examples/`.

Despite this, I'm not sure if that proves I haven't introduced a regression for #12 and 9fe7e3f0420, so you might want to double check that as I'm unfamiliar with that particular issue..

Fixes #29.

### CODE REVIEW

File: lib/jekyll-paginate-v2/generator/paginationModel.rb [hunk 1]
```diff
@@ -227,12 +227,14 @@ def paginate(template, config, site_title, all_posts, all_tags, all_categories,
             puts "Pagination: ".rjust(20) + "Rolling through the date fields for all documents"
           end
           for p in using_posts
-            tmp_date = p.date
-            if( !tmp_date || tmp_date.nil? )
-              if @debug
-                puts "Pagination: ".rjust(20) + "Explicitly assigning date for doc: #{p.data['title']} | #{p.path}"
+            if p.respond_to?('date')
```
Comment (sverrirs) [inline lib/jekyll-paginate-v2/generator/paginationModel.rb]: Hey Peter, sorry for the long delay I have been a little busy with real life these days. I like this solution but you're right I will have to check how it will interact with the `--drafts`` bug this ugly codeblock is attempting to "fix"

**Comment by sverrirs** [comment]
Wow.. this tool a while! :) Sorry about the delay but the generator looks as though it is perfectly ok with this change and there is no regression. Merging this.

Thanks for taking the time to improve this plugin :+1:
